jenkinsci/azure-storage-plugin

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStorageClient.java
1) Extra / in blob URI path for the archive zip removed.
2) Use better way to get output stream for the zip archiver.
/cc @snallami
> Two minor fixes:

- src/main/resources/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher/global.jelly
made storage account key hidden
@mmitche
> made storage account key hidden

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStorageClient.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/Constants.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/Utils.java
adding user-agent for tracking azure storage plugin telemetry
> Add telemetry

- exclude-findbugs.xml
- pom.xml
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureBlobAction.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBuilder.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStorageClient.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/Utils.java
Please give it a look and make findbugs happy
> fix errors to make maven-findbugs happy

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureCredentials.java
> Replace credentials getter names so they match with the jelly file

- pom.xml
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureCredentials.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/CredentialMigration.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/Utils.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/beans/StorageAccountInfoTest.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureCredentialsTest.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/helper/CredentialMigrationTest.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/helper/UtilsTest.java
added unit tests for storage plugin ....
adding all tests at the same time can be a problem for the reviewer, so  integration tests will be in a different pull request.
> added unit tests for storage plugin

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStorageClient.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher.java
- src/main/resources/com/microsoftopentechnologies/windowsazurestorage/Messages.properties
> Add more logs to help debug

- pom.xml
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadToFileService.java
- src/main/resources/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher/config.properties
- src/main/resources/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher/global.jelly
- fix error cannot add storage account in system configuration page
- update developer info
- update README
> fix error cannot add storage account in system configuration page

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/Constants.java
This fixes https://issues.jenkins-ci.org/browse/JENKINS-45161
> Add null check for string configuration fields and fix default storage type

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureUtils.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/DownloadFromFileService.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadToFileService.java
- src/main/webapp/help-blobEndPointURL.html
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureUtilsTest.java
> Support secure transfer for file upload/download

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/Constants.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/Utils.java
> Allow root container

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher.java
fix https://github.com/jenkinsci/windows-azure-storage-plugin/issues/82.
remove container/share name from ctor since ctor parameters are required and will break pipeline.
> fix issue https://github.com/jenkinsci/windows-azure-storage-plugin/issues/82

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureBlobProperties.java
Fix issue https://github.com/jenkinsci/windows-azure-storage-plugin/issues/89
explicitly specify mime type for js files since Tika has a known issue to handle js files
> fix issue #89

- pom.xml
the versions of 'org.bouncycastle:bcpkix-jdk15on' and 'org.bouncycastle:bcprov-jdk15on' are conflict.
> Update pom.xml to resolve the IT failure.

- src/main/resources/com/microsoftopentechnologies/windowsazurestorage/AzureBlobAction/index.jelly
Fix issue #104 .
For reference:
https://wiki.jenkins.io/display/JENKINS/Basic+guide+to+Jelly+usage+in+Jenkins#BasicguidetoJellyusageinJenkins-PredefinedURLs
> Fix image broken in Azure Artifacts.

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadService.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadToBlobService.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadToFileService.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/model/UploadServiceData.java
- src/main/resources/com/microsoftopentechnologies/windowsazurestorage/Messages.properties
Related with PR #102 .
We can also use several threads to speed up our uploading stage.
> Upload files in several threads

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadService.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/model/UploadServiceData.java
- src/main/resources/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher/config.jelly
- src/main/resources/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher/config.properties
- src/main/webapp/help-onlyUploadModifiedArtifacts.html
Related with issue #52 .
User can have an option to choose whether only upload artifacts modified in current build.
> Add option for only upload modified artifacts in this build

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher.java
> Fix artifacts panel issue #128

- pom.xml
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/DownloadService.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadService.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadToFileService.java
Fix issue #111 . Upgrade storage sdk to 6.1.0 version which is used by Azure sdk too.
> Upgrade Azure storage sdk to version 6.1.0

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/DownloadFromFileService.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/WindowsAzureStorageTest.java
[JENKINS-56317](https://issues.jenkins-ci.org/browse/JENKINS-56317)
> Fix download share file ant syntax issue

- pom.xml
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureBlobMetadataPair.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureBlobProperties.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureCredentialsTest.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/helper/CredentialMigrationTest.java
Initial bump needed for configuration as code support, tests are failing locally, seeing if any different on CI
Incompatibility with JCasC so far is the credential in this has the same symbol as the azure credentials plugin
> Bump jenkins core baseline

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureUtils.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadService.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureUtilsTest.java
Call put block list api to upload large files.
[JENKINS-56506](https://issues.jenkins-ci.org/browse/JENKINS-56506)
> Add support for uploading large files

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadService.java
Uploading small files does not need the blockId parameter
> Small files no need to use blockid

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadService.java
[JENKINS-58174](https://issues.jenkins-ci.org/browse/JENKINS-58174)
> Delete temporary directory after uploading

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadService.java
[JENKINS-58633](https://issues.jenkins-ci.org/browse/JENKINS-58633)
> Add metadata for block list file

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadService.java
[JENKINS-59748](https://issues.jenkins-ci.org/browse/JENKINS-59748)
> No need to check uploaded count when only uploading archived file

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureBlob.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureBlobAction.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBuilder.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureUtils.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/Utils.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/DownloadFromBuildService.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadService.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/model/UploadServiceData.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/helper/UtilsTest.java
Draft as I still want to check if the same file path different contents across different accounts works
fixes https://github.com/jenkinsci/azure-storage-plugin/issues/184
> Download blobs across storage accounts

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBuilder.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/DownloadFromBuildService.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/DownloadFromContainerService.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/DownloadFromFileService.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/DownloadService.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadService.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/model/ServiceData.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/model/UploadServiceData.java
- src/main/resources/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBuilder/config.jelly
- src/main/resources/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBuilder/help-verbose.html
- src/main/resources/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher/config.jelly
- src/main/resources/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher/help-verbose.html
Fixes https://github.com/jenkinsci/azure-storage-plugin/issues/175
> Make logging on upload/download quiet by default

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureStorageAccount.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureUtils.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadService.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadToBlobService.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/ConfigAsCodeTest.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/helper/CredentialRenameTest.java
https://github.com/Azure/Azurite
> Add storage emulator support

- pom.xml
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadService.java
Fixes https://github.com/jenkinsci/azure-storage-plugin/issues/189
Requires new SDK from https://github.com/jenkinsci/azure-sdk-plugin/pull/11
> Large file support for file share

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadToFileService.java
Fixes https://github.com/jenkinsci/azure-storage-plugin/issues/210
relates to https://github.com/Azure/azure-sdk-for-java/issues/26867
I verified that blobs doesn't have this issue
> Handle uploading empty file

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadToFileService.java
- src/main/resources/com/microsoftopentechnologies/windowsazurestorage/AzureBlobAction/index.jelly
Fixes https://github.com/jenkinsci/azure-storage-plugin/issues/214
> Add folder path to fileshare upload to allow downloading it

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/DownloadFromFileService.java
Fixes https://github.com/jenkinsci/azure-storage-plugin/issues/232
Removal of return statement that leads to termination of recursion when multiple directories match ant syntax.
> Search multiple directories when downloading files

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureCredentialsBinding.java
see https://github.com/jenkinsci/azure-storage-plugin/pull/280#issuecomment-1857735681
Removed a cdn endpoint url from credentials.xml and then created a test pipeline with https://github.com/jenkinsci/azure-storage-plugin/pull/280#issuecomment-1857735681
Could reproduce before and couldn't after.
```[tasklist]
```
> Fix null Azure CDN endpoint variable on credential binding

- pom.xml
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher.java
- src/main/resources/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher/global.jelly
- src/main/resources/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher/global.properties
- src/main/resources/global.properties
- src/main/resources/lib/azure-storage/credentials.js
- src/main/webapp/help-storageaccounts.html
Followed https://github.com/jenkinsci/credentials-plugin/blob/master/docs/consumer.adoc for cleaning up the credentials code
Followed https://www.jenkins.io/doc/developer/security/csp/ for CSP
YUI spreadsheet for yui adaption: https://docs.google.com/spreadsheets/d/1UjvtFmNmEdjMN5DUoFxJfBryA8q-E5_HwOzVKbVG9b0/edit?gid=0#gid=0
Cleaned up the UI while I was touching this code, looks like lots of dead cruft from a previous migration that wasn't cleaned up
Manually clicked the button and the dialog still appears
> Make CSP compatible and remove YUI

- src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher.java
- src/main/resources/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher/config.jelly
Fixes https://github.com/jenkinsci/azure-storage-plugin/issues/322
Used snippet generator and made sure all the changed endpoints were being hit correctly
Installed CSP plugin and verified issues were being triggered before and not after
> Remove more CSP issues

- Jenkinsfile
- pom.xml
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureBlobAction.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBuilder.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureStorageAccount.java
- src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/CredentialMigration.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/helper/CredentialMigrationTest.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/helper/CredentialRenameTest.java
> Migrate from EE 8 to EE 9

- src/test/java/IntegrationTests/FileStorageDownloadIT.java
- src/test/java/IntegrationTests/FileStorageUploadIT.java
- src/test/java/IntegrationTests/IntegrationTest.java
- src/test/java/IntegrationTests/WAStorageClientDownloadIT.java
- src/test/java/IntegrationTests/WAStorageClientUploadIT.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/AzureStorageTest.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/ConfigAsCodeTest.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/beans/StorageAccountInfoTest.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureStorageAccountTest.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/helper/CredentialMigrationTest.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/helper/CredentialRenameTest.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/helper/UtilsTest.java
- src/test/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadServiceTest.java
This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations and imports
* Migrate assertions
* Remove public visibility for test classes and methods
* Minor clean up
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewed.
If there are any questions, please do not hesitate to ping me.
> Migrate tests to JUnit5
