jenkinsci/azure-storage-plugin

src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBuilder.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/Utils.java, src/test/java/com/microsoftopentechnologies/windowsazurestorage/WindowsAzureStorageTest.java
If one wants to use https://blob.core.windows.net/, or some other non-default URL to Azure Storage,
the host part of the URL will be prepended with the storage account of the build.
Example:
1. The blob service endpoint URL is set to https://blob.core.windows.net for account 'foo-account'
2. First build publishes its artefacts successfully to https://foo-account.blob.core.windows.net
3. Second build fails to publish the build artifacts with the following error message:
```
Archiving artifacts
Failed to validate storage account details. Please verify storage account name and key. If you are using a private or other Windows Azure cloud service, make sure that the blob endpoint url is correct.
Storage Account name --->foo-account<----
Blob end point url …
```
=> Remove prepend of account name to custom service URL

.gitignore, pom.xml, src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStorageClient.java
Hi, this is a very simple fix, just upgrading the SDK version.
=> use latest azure storage SDK to avoid "The value for one of the HTTP headers is not in the correct format" error

pom.xml, src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBuilder.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStorageClient.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureCredentials.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/Constants.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/CredentialMigration.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/Utils.java, src/main/resources/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBuilder/config.jelly, src/main/resources/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher/config.jelly, src/main/resources/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher/global.jelly, src/main/resources/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher/global.properties, src/main/resources/com/microsoftopentechnologies/windowsazurestorage/helper/AzureCredentials/credentials.jelly, src/main/resources/global.properties, src/main/webapp/help-storageaccounts.html, src/main/webapp/help-storagecredential.html, src/test/java/com/microsoftopentechnologies/windowsazurestorage/WindowsAzureStorageTest.java
Following are the changes:
1. Moved storage account config to Jenkins credential store which is more secure the original xml file  for storage config.
2. Upgrading plugin to 0.3.3 or future from an old version won't break any existing jobs.
3.  Storage Accounts can be added to credential store via credentials page from Jenkins dashboard, system configuration page as previous and job configuration page (new).
=> Make storage safe

src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureBlobAction.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher.java
AzureBlobAction was not updated after the credentials move to Jenkins Credentials Store.
* Updated WAStoragePublisher to pass the credentials id to AzureBlobAction (if available)
* Updated AzureBlobAction to AzureCredentials.getStorageCreds which fetches the storage account information with or without a valid credentialsId (matches both scenarios: "job created with latest storage plugin, or job created with a version <= 0.3.2
=> Fix AzureBlobAction [FIXED JENKINS-42726]

.gitignore, src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStorageClient.java
- While computing the file hash and size we weren't explicitly closing the stream.
- Changed the code around stream to look nicer (using try(resource acquisition){} idiom instead of try{}finally{ release resource} )
Before merging we need to verify that #49 is actually fixed
=> Make sure the file streams are closed after download or upload

src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBuilder.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBuilderContext.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStorageClient.java, src/main/resources/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBuilder/config.jelly, src/main/resources/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBuilder/config.properties, src/main/webapp/help-deleteFromAzureAfterDownload.html, src/test/java/IntegrationTests/WAStorageClientDownloadIT.java
resolve https://github.com/jenkinsci/windows-azure-storage-plugin/issues/42 by:
- adding an option in advanced settings. If it's checked the original copy on azure will be deleted after downloaded to local
- add `AzureStorageBuilderContext` as a model class to avoid too many parameters in method signatures.
- remove duplicated code blocks.
- fix affected unit tests.
Testing performed:
- download files
- download files recursively
- download files with exclusion
- download files with `flatten` enabled
- download files with `delete from azure` enabled
=> resolve issue #42 

pom.xml, src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureBlobProperties.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStorageClient.java, src/main/resources/com/microsoftopentechnologies/windowsazurestorage/AzureBlobProperties/config.jelly, src/main/resources/com/microsoftopentechnologies/windowsazurestorage/AzureBlobProperties/config.properties, src/main/resources/com/microsoftopentechnologies/windowsazurestorage/AzureBlobProperties/help-detectContentType.html, src/test/java/IntegrationTests/WAStorageClientUploadIT.java, src/test/java/com/microsoftopentechnologies/windowsazurestorage/AzureBlobPropertiesTest.java
This PR gives user an option to auto detect content type of the blob based on the file name and content.
The detection ability is provided by [Apache Tika](https://tika.apache.org/).
=> Provide an option to auto detect content type

pom.xml
remove integration test from verify phase because the integration test broken our CI process for required environment variables cannot be read correctly.  Since the integration tests are already included in CI, just remove it from verify phase to avoid duplication.
=> remove integration test from verify phase

pom.xml, src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureBlobAction.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureUtils.java
fix issue https://github.com/jenkinsci/windows-azure-storage-plugin/issues/84: cannot download artifact.
The root cause is that the download link can only support Azure Blob Storage. Azure files are handled in the  same way as Azure blob. Definitely the blob cannot find and download as expected.
=> fix issue #84: cannot download artifacts

src/main/resources/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher/global.jelly
fix https://github.com/jenkinsci/windows-azure-storage-plugin/issues/85: blank window shown while configuring storage credentials in Jenkins Global configuration page.
It's caused by an extra forward slash in url. In cases where the context path is a empty string, the ajaxUrl becomes something like "//path...". The right url should be "/path..." starting with a single forward slash. The two have quite different meanings.
It happens to be right when the context path is not empty where the url "/jenkins//path..." is usually interpreted as the '/jenkins/path...'
=> fix #85: blank window issue while configure storage credentials globally

src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBuilder.java, src/main/resources/com/microsoftopentechnologies/windowsazurestorage/Messages.properties
Fix issue 42341: https://issues.jenkins-ci.org/browse/JENKINS-42341.
=> fix jenkins-42341:marking build as UNSTABLE when no files downloaded

pom.xml, src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureCredentialsBinding.java, src/main/resources/com/microsoftopentechnologies/windowsazurestorage/Messages.properties, src/main/resources/com/microsoftopentechnologies/windowsazurestorage/helper/AzureCredentialsBinding/config-variables.jelly, src/main/resources/com/microsoftopentechnologies/windowsazurestorage/helper/AzureCredentialsBinding/config-variables.properties
fix #99 : To use the credentials binding with Azure storage, use the following:
```
withCredentials([azureStorage(blobEndpointUrlVariable: 'BLOB_URL', credentialsId: 'CREDENTIALS_ID', storageAccountKeyVariable: 'STORAGE_KEY', storageAccountNameVariable: 'STORAGE_NAME')]) {
sh '''
echo "$BLOB_URL, $CREDENTIALS_ID, STORAGE_KEY, STORAGE_NAME"
'''
}
```
=> Add credentials binding support for azure storage

src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/DownloadFromBuildService.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/DownloadFromContainerService.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/DownloadFromFileService.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/DownloadService.java, src/main/resources/com/microsoftopentechnologies/windowsazurestorage/Messages.properties
Fix issue #86 : azure storage plugin takes a lot of time especially when large numbers of files need to be downloaded. The origin design is scanning all the items and downloading one if it matches the requirements in a single thread. Now , a thread will scan all the items and put one into a queue if it matches the requirements. At the same time, several threads will check the queue and download the items.
I have made some tests on my laptop.
for container with 800 small files:
|Version|Round 1|Round 2|Round 3|AVG|
|--|--|--|--|--|
|old|9'2''|8'45''|9'15''|9'1''|
|new|46''|46''|46''|46''|
for share files with 800 small files:
|Version|Round 1|Round 2|Round 3|AVG|
|--|--|--|--|--|
|old|9'15''|9'29''|8'54''|9'13''|
|new|42''|40''|42''|41''|
=> Download items in several threads.

src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBuilder.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureCredentials.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureUtils.java
Fix issue #31 .
Windows Azure Storage Plugin could only rely on JVM proxy in the past which is not appropriate in some cases.  And Jenkins has its own proxy setting, details in https://wiki.jenkins.io/display/JENKINS/JenkinsBehindProxy . We can set default proxy for Azure Storage SDK with proxy setting from Jenkins before we send any http request.
=> Use Proxy from Jenkins

pom.xml, src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureBlobAction.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBlueArtifact.java
Add feature referred in issue #101 .
Now Azure Storage artifacts can be seen or downloaded on blue ocean .
Shown as :
=> Blue ocean artifact

src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadService.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadToFileService.java
Related with PR #103 .
When uploading artifacts to share files, we need to check if the directory exists first.  If doing this in `uploadCloudFile` method which would be executed in several uploading threads without concurrency control, it may cause exception like below:
```
com.microsoftopentechnologies.windowsazurestorage.exceptions.WAStorageException: fail to create directory.
at com.microsoftopentechnologies.windowsazurestorage.service.UploadService.ensureDirExist(UploadService.java:301)
at com.microsoftopentechnologies.windowsazurestorage.service.UploadService.uploadCloudFile(UploadService.java:262)
at com.microsoftopentechnologies.windowsazurestorage.service.UploadService$UploadThread.run(UploadService.java:101)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51 …
```
=> Fix ensuring directory exist in multi thread bug.

src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/Constants.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/Utils.java, src/test/java/com/microsoftopentechnologies/windowsazurestorage/WindowsAzureStorageTest.java
Related with issues #119 .
[static website](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website)  is hosted in a special container named "$web". Change the container name validation rules to let it pass.
=> Change container name validation for static website hosting

src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBlueArtifact.java
While using the plugin we recognised that the url behind artifacts in blue ocean does not point correctly to the corresponding Azure blob. Instead of /job/JOB_NAME/BUILD_NUMBER/Azure/processDownloadRequest/... it points to /job/STORAGE_NAME/Azure/processDownloadRequest/BLOB_NAME, which is an invalid path. I adjusted the respective function in the AzureStorageBlueArtifact class to return the correct url.
=> Corrected URL for Blue Ocean artifacts

src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBuilder.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/Utils.java
Use same replaceMacro for the same field in both publish and download process.
changes include:
- transfer replaceMacro methods from WAStoragePublisher.java to Utils.java
- use replaceMacro.tolowercase() for `containerName` and `sharefileName`
- use replaceMacro.trim() for `includeFilesPattern` and `excludeFilesPattern`
related issue #125
=> Fix naming convention rules not consist issue

pom.xml, src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureBlobAction.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBuilder.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher.java
Fix #134 . Use get**Type() methods to give default value of blob storage since the previous version only support blobs.
=> Compat with old version when upgrading plugin

src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureBlobAction.java
Hey everyone,
we use the Pipeline Multibranch plugin for our integration with GitLab, so we get branch names with a "/" in it, which gets encoded to "%2F" and blob.getBlobName().equals(blobName) == false.
And because of that, it is impossible to download an artifact with a "/" in the name from our storage account. 
I did two things first of all I imported the URLDecoder library to compare the decoded names.
And then instead of using the blobName for the SAS URL, I used the blob.getBlobName() because the encoded blob Name is the one that is used to store the blob in Azure.
=> Couldn't download artifacts, when there was a "/" in the blob name. 

src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/Constants.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/Utils.java, src/test/java/com/microsoftopentechnologies/windowsazurestorage/helper/CredentialMigrationTest.java
The portal defaults to requiring https access, should be no reason these
days to default to http
I was confused why my setup was failing to validate, it took me a minute
of checking to notice that the default didn't work out of the box.
Small change that should be a good QoL improvement
=> Change default blob URL to https

src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/DownloadFromBuildService.java
Synchronized the blob list to prevent the build serialization job to access it and throw `ConcurrentModificationException `.
[JENKINS-57553](https://issues.jenkins-ci.org/browse/JENKINS-57553)
=> Fix ConcurrentModificationException for blob actions

pom.xml, src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadToBlobService.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadToFileService.java
Inspired by reviewing #156.
The cleanup logic was put in the `getCloudBlobContainer` or `getCloudFileShare` method which is called when uploading individual files and archived file. So if one user chooses both cleanup  and uploading archived file. The individual files will be cleaned when uploading archived one.
Solution: When only uploading individual files or archived file, we will try to trigger cleanup. When we need to upload both of them, we only try to cleanup in the individual round since it is executed before the archived one.
=> Fix possible duplicating cleanup

src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadService.java
Use several `DigestUtils.**` methods will consume the stream several times, causing the later one gets empty stream. This causes the `mdBytes`  always the same as empty file. Try to get the md5 value once and encode it here.
=> Fix wrong md5 value

pom.xml, src/test/java/com/microsoftopentechnologies/windowsazurestorage/ConfigAsCodeTest.java, src/test/java/com/microsoftopentechnologies/windowsazurestorage/helper/CredentialRenameTest.java, src/test/resources/com/microsoftopentechnologies/windowsazurestorage/helper/CredentialRenameTest/testRenameStorageConfig/credentials.xml
JCasc had to create a new dependency that wasn't a `tests` classifier because maven doesn't allow you to bring dependencies through classifiers.
Upgrading here so that PCT works again,
Tracking:
https://github.com/jenkinsci/bom/pull/164
=> Upgrade to new jcasc test harness

src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadService.java
Uploading files that were greater than `100 * 1000 * 1000` SI bytes (100 MB) would fail to upload due to a `400 Bad Request`.
```
ERROR: MicrosoftAzureStorage - Error occurred while uploading to Azure - sharedst01
com.microsoftopentechnologies.windowsazurestorage.exceptions.WAStorageException: Fail to upload individual files to blob
at com.microsoftopentechnologies.windowsazurestorage.service.UploadToBlobService.uploadIndividuals(UploadToBlobService.java:151)
at com.microsoftopentechnologies.windowsazurestorage.service.UploadService.execute(UploadService.java:719)
at com.microsoftopentechnologies.windowsazurestorage.WAStoragePublisher.perform(WAStoragePublisher.java:438)
at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
at …
```
=> Calculate block size in SI base

src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureBlobProperties.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBuilder.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/Constants.java, src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/CredentialRename.java, src/main/resources/com/microsoftopentechnologies/windowsazurestorage/AzureBlobMetadataPair/config.jelly, src/main/resources/com/microsoftopentechnologies/windowsazurestorage/AzureBlobProjectAction/jobMain.jelly, src/main/resources/com/microsoftopentechnologies/windowsazurestorage/AzureBlobProperties/config.jelly, src/main/resources/com/microsoftopentechnologies/windowsazurestorage/Messages.properties, src/main/resources/index.jelly, src/main/webapp/help-storageaccounts.html
Empty strings won't show up for optional fields anymore
```
azureDownload containerName: 'jenkins', downloadType: 'container', includeFilesPattern: 'hello*.txt', storageCredentialId: 'storage'
```
```
azureUpload blobProperties: [], containerName: 'jenkins', filesPath: 'hello*.txt', storageCredentialId: 'storage', storageType: 'blobstorage'
```
not sure how to get rid of the empty blob properties but better than it was anyway
=> Simplify pipeline syntax generator

src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/UploadService.java
Not sure why but I noticed when uploading an 800mb file this was null.
I assume we can live without it, better not to fail. Can report upstream if others really need this info.
=> Don't fail if file hash is null

src/main/resources/com/microsoftopentechnologies/windowsazurestorage/WAStoragePublisher/config.jelly
Fixes https://github.com/jenkinsci/azure-storage-plugin/issues/212
Pipeline syntax will no longer generate an empty `[]` which doesn't work.
You need to either omit it or include at least one field.
=> Don't include optional blob properties in generated pipeline script

src/main/java/com/microsoftopentechnologies/windowsazurestorage/service/DownloadService.java
I make extensive use of "Download artifact from build -> Upstream build that triggered this job". As of today, this throws:
```
com.azure.storage.blob.specialized.BlockBlobClient cannot be cast to com.azure.storage.file.share.ShareFileClient
```
This doesn't work with the current mix of Azure plugin dependencies on an up-to-date Jenkins install. The core issue is when the download items are enumerated, they are of type `BlockBlobClient` not `BlobClient` - the `instanceof` check therefore falls through into the `ShareFileClient` case, and that's not a valid cast.
Instead, check for the parent type of both `BlobClient` and `BlockBlobClient`, `BlobClientBase`. This is valid for the current case _and_ the old case, so should be safe for various combinations of dependency versions.
=> Fix BlockBlobClient cast error downloading from job

.mvn/extensions.xml, pom.xml
We use six digits for the snapshot, I guess that is just a typo 👀
=> Fixup CD snapshot format

pom.xml, src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBlueArtifact.java
Fixes #278 
As a user of the azure-storage plugin who doesn't use BO at all, it's frustrating that I need this dependency installed.
Would you strongly object to removing the BO integration all together @timja?
It was added in 2018 when BO was alive, but 6 years later, it's declared abandoned and EOL. I see no real reason why we should keep up an integration for an end-of-life plugin.
=> Remove mandatory install of blue ocean plugin
